version: '3.8'

# Docker Compose configuration optimized for macOS
# Uses web interface by default due to X11 and camera limitations on macOS

services:
  # Web interface version (recommended for macOS)
  fitlifeposture:
    image: fitlifeposture:latest
    container_name: fitlifeposture_app
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - PYTHONUNBUFFERED=1
      - INTERFACE_MODE=web  # Web mode by default on macOS
      - CAMERA_INDEX=0
    
    ports:
      - "8080:8080"
    
    volumes:
      # Data persistence
      - ./reports:/app/reports
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Note: Camera access is limited on macOS Docker
    # The app will work but may not detect cameras
    
    restart: unless-stopped

  # GUI version (requires XQuartz)
  fitlifeposture-gui:
    image: fitlifeposture:latest
    container_name: fitlifeposture_gui
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - PYTHONUNBUFFERED=1
      - INTERFACE_MODE=gui
    
    ports:
      - "8080:8080"
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./reports:/app/reports
      - ./data:/app/data
      - ./logs:/app/logs
    
    restart: unless-stopped
    profiles:
      - gui

# Default service runs web interface on macOS
# To run GUI version: docker-compose --profile gui up
# Note: GUI requires XQuartz to be installed and configured
